### PR TITLE
New textures for SimpleOres and Fusion

### PR DESCRIPTION
**Pull request by Thombias**
Updated textures for both SimpleOres and Fusion to fit the 1.14+ default style.
This is a resource pack for previewing purposes, simply load it while having both SimpleOres and Fusion installed.
If you'd like to include them into future updates, feel free to do so. ^^

Dropbox Link: https://www.dropbox.com/s/clg04s9v3k1cqx4/Updated%20Simpleores%20%2B%20Fusion%20Textures.zip?dl=0
(I hope this works.)

P.S.: If you do include them, i'd be really happy if you could put me as artist or texture artist (Or whatever curseforge calls it) to the project. :D

### CODE REVIEW

**Comment by Sinhika** [comment]
Might have been better to open this as an issue, as this is a stand-alone texture pack. That being said, I turned both your submission and the original textures into texture packs, so I could switch between the two and consider them. At first, I was put off by some of the changes, but after studying and comparing with vanilla textures, I see that what you primarily did was change the textures to match the style of the newer vanilla textures. Oh, and thank you very much for fixing the fugly old fusion furnace texture!  I wasn't sure I liked the change in tint to tin, but I realized that the new tint and textures stand out better from silver ore and silver, iron, onyx, and steel ingots, tools and armor, all of which are quite similiar. Therefore, I will accept and use them.

I think the new metal block textures in the style of new iron blocks need a bit of work--the ribbing is a bit too obtrusive, and not subtle like that of iron. However, I will pick them up for now. The only block I don't think I'll use is onyx block; I prefer the old onyx texture, and the onyx furnaces from Machines are using that texture.

I plan to incorporate most of your textures into SimpleOres and Fusion, but make the "classic" textures available as a resource pack, and ditto for your original texture pack with the revised onyx block. (At some point I ought to grab the old Soartex Fanver textures for SimpleOres and update them, too.)

ETA: I plan to license the texture packs under CC-BY-SHAREALIKE 4.0, as that is about as close to the LGPL license as you can get with a CC artwork license, and I need the licensing terms to be compatible with the license on the mod that uses the textures. Is this okay with you? If not, we need to discuss terms. Note that both CC and LGPL include an attribution term, so your name will be on the artwork.

**Comment by Thombias** [comment]
I barely ever use Github, so i thought it made more sense to post it here than in the issues tab. I always thought the issues tab was only meant for reporting bugs and such, but apparently that isn't the case?

Either way, thank you for taking the time to look at my texture changes and also thanks for your critique! I admit, at first i noticed the obtruse ribbing for the copper, tin, bronze and steel storage blocks too, but i thought "Nah, i'm thinking too much into this, let's see what he says and then i'll decide if i adjust them"

And so i did. I've adjusted these ore storage block textures a bit. I hope they're much better now. ^^
If you want to take a look at them, here's a new version of the resource pack that has the adjusted ore storage blocks:
https://www.dropbox.com/s/bxmy0kwqbpmj1wj/Updated%20Simpleores%20%2B%20Fusion%20Textures%20V2.zip?dl=0

As for the change in tint for tin ore, tools & armor... i feel like it was absolutely necessary to change tin like this. From a gameplay perspective, the old tin and steel textures weren't really optimal. Some ores could've easily been mistaken for another ore, inluding their tools, armor and weapons, especially when you have tin, iron, steel and silver all in your game. It's really difficult to tell them apart sometimes. Even in real life they look very similar if further processed & polished. (At least for me)

I actually took inspiration from Terraria, which gave tin ore and gear a similar tint, mine came out a bit brighter though. But still i think it fits well for Minecraft. Video games don't need to adhere to real life anyway, especially for a game like Minecraft.

I changed mythril and adamantium mostly by personal taste. Mythril would've fit a more purple tint better, since it's the most enchantable of the bunch. I wanted adamantium to look more shiny and pretty, so it required a very slight cyan tint to make the shine work, it's still fairly green though, just with a tiny little bit of cyan.

However i don't think i can do much for the onyx storage block texture. Onyx ist just like diamond a gem and shares the same texture, just in a different color. And therefore i wanted to give onyx the same textures from diamond, storage block and all, to make it consistent. I'm fine if you don't want to use it. (I never have enough to craft them in my modded worlds anyway lmao)

Very glad though that you like my new fusion furnace texture! At first i really wasn't sure how i could make it work. I tried to combine the newer vanilla brick texture with the blast furnace texture and this was the result. Since the fusion furnace can only process ores, the blast furnace look fits it well i think. Like the tin texture this was a result from the question: "How would i change it from a gameplay perspective?" With this texture players won't mistake it for an upgraded default furnace, hopefully.

I was fully expecting you wouldn't use everything, as like i've said in my comment on the curseforge page, it's was actually meant only for personal use, not publicly. But now i've spent so much time on this that i feel it deserves to be included in both mods. :D

Do whatever you think is necessary for the licensing part. I'm not experienced enough in licensing, copyright and all that.
These are just mostly recolored vanilla textures anyway. I'm fine with anything, really. :)

**Comment by Sinhika** [comment]
For some reason the new package had nether versions of adamantium ore and mythril ore; I reverted those. Your complete pack, with proper pack.png and a more elaborate pack.mcmeta, is now archived at https://github.com/Sinhika/ThombiasSimpleOresTextures/tree/1.15. I will be making 1.14.4 and 1.16.3 versions of the pack as well as incorporating the parts of it discussed above into SimpleOres and Fusion.  I have also archived the "classic" SimpleOres & Fusion texture packs in anothe r GitHub repository.

**Comment by Thombias** [comment]
Oops, i accidentally posted my personal version instead of the public one. I let Mythril & Adamantium generate in the nether for the modpack i'm working on, otherwise i would have way too many ores in the overworld. (I already have copper. tin, silver & platinum + the vanilla ores)
Sorry, if i'm annoying you again with this, but i released another version:

https://www.dropbox.com/s/ttoazxgimx61zou/Updated%20Simpleores%20%2B%20Fusion%20Textures%20V3.zip?dl=0

I did a little mistake because i haven't actually tested and compared the V2 textures before posting the previous comment. Now i've actually placed them side by side and compared them with iron. The contrast was still too high. This version 3 is what i consider the absolute final version. I've tested it this time before posting this comment and now they no longer look so out-of-place, when placed right next to iron blocks. The Mythril & Adamantium ores are also fixed.
Please use this version and not the older ones.

**Comment by Sinhika** [comment]
That looks good. I'll be rolling it into SimpleOres and Fusion, as previously mentioned. The texture packs now have their own projects, as well, so I can package them separately. If you have any more changes, just do a PR against this one:

https://github.com/Sinhika/ThombiasSimpleOresTextures

> Do whatever you think is necessary for the licensing part. I'm not experienced enough in licensing, copyright and all that.
These are just mostly recolored vanilla textures anyway

Seriously, in the future, decide what rights you want to exercise in licensing your work. That way, you know what you are allowing other people to do with your stuff (e.g., the license I've stuck on my stuff means no one can legally take it and make a closed-source, proprietary game out of it, but they can use it in modpacks and for their own mods all they like, as long as it is also open-source), and other people know what they are allowed to do with your stuff. (E.g, modpack developers generally can't use mods that don't have a license that allows redistribution in a modpack, so they avoid such mods). The legal default if you don't stick an explicit license on something is "All rights reserved", which means no one else can copy your stuff. Or use it in a modpack or another mod.

The Creative Commons site, and the GNU Public License site have human-readable explanations for what their license templates cover. They are worth being familiar with.  GPL is mostly for code, whereas Creative Commons (CC) was developed to cover art and text, which the code-specific GPL didn't handle very well.

 Since these are recolored vanilla textures, I think the CC-by-SA and LGPL licenses should be compatible with Mojang's license.

**Pull request closed without merging**
